export type TrendStatus = 'hot' | 'rising' | 'fading';

/**
 * Extended platform list — all 7 platforms tracked by Nemo.
 * Platform weights (Cross-Platform Score): TikTok 22%, Instagram 20%, YouTube 20%,
 * Google Trends 18%, Twitter/X 12%, Reddit 5%, LinkedIn 3%.
 */
export type TrendPlatform = 'google' | 'youtube' | 'instagram' | 'linkedin' | 'tiktok' | 'twitter' | 'reddit';

export type TrendContentType = 'TOPIC' | 'HOOK' | 'CONCEPT' | 'KEYWORD';

export interface TrendItem {
  id: string;
  title: string;
  category: string;
  status: TrendStatus;
  nemoScore: number;

  /**
   * Sub-scores aligned with Nemo Backend Data Signals & Trend Scoring Review v1.0
   * Formula: (cvs×0.25 + ss×0.30 + cps×0.25 + freshness×0.20) × freshnessMultiplier
   */
  cvs: number;           // Creator Velocity Score 0–100 (was 0–1 range — corrected)
  ss: number;            // Spike Score 0–100 log-normalized (was raw ratio — corrected)
  cps: number;           // Cross-Platform Score 0–100 (was missing — now required)
  freshness: number;     // Freshness Score 0–100 (was 0–1 range — corrected)
  freshnessMultiplier: number; // 0.1–1.0 final multiplier applied to composite score

  platforms: TrendPlatform[];
  creatorsCount: number;
  mentions24h: number;
  mentionsPrev24h: number;    // required for Spike Score formula
  creatorsLast6h: number;     // required for Creator Velocity Score (corrected formula)
  creatorsLast24h: number;    // required for Creator Velocity Score
  creatorsLast72h: number;    // required for Creator Velocity Score (denominator)
  sparklineData: number[];
  timeAgo: string;
  firstDetectedAt: string;    // ISO timestamp — required for Freshness Multiplier
  hashtags: string[];
  description: string;
  isBookmarked: boolean;
  velocity: number;
  spike: number;
  contentType: TrendContentType;
  trendingAudio?: string;

  // New signals from document
  geoRegions?: string[];
  breakoutBoolean?: boolean;
  queryClusterId?: string;
  geoSpreadScore?: number;
  engagementVelocity?: number;
}

export const MOCK_TRENDS: TrendItem[] = [
  {
    id: 'trend-001',
    title: 'Claude AI Tool Integrations',
    category: 'AI & Tech',
    status: 'hot',
    nemoScore: 91,
    cvs: 88,
    ss: 75,
    cps: 62,
    freshness: 100,
    freshnessMultiplier: 1.0,
    platforms: ['google', 'youtube', 'linkedin'],
    creatorsCount: 4821,
    mentions24h: 128400,
    mentionsPrev24h: 31200,
    creatorsLast6h: 820,
    creatorsLast24h: 2100,
    creatorsLast72h: 4821,
    sparklineData: [20, 35, 28, 52, 48, 71, 88, 95, 91],
    timeAgo: '2h ago',
    firstDetectedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    hashtags: ['#ClaudeAI', '#AITools', '#MCP', '#Automation', '#LLM'],
    description: 'Claude AI tool integrations and MCP server configurations are exploding across developer and creator communities.',
    isBookmarked: true,
    velocity: 2.4,
    spike: 312,
    contentType: 'TOPIC',
    geoRegions: ['US', 'IN', 'UK', 'DE', 'CA'],
    geoSpreadScore: 5,
  },
  {
    id: 'trend-002',
    title: 'Instagram Broadcast Channels',
    category: 'Marketing',
    status: 'hot',
    nemoScore: 84,
    cvs: 76,
    ss: 68,
    cps: 42,
    freshness: 100,
    freshnessMultiplier: 1.0,
    platforms: ['instagram', 'youtube'],
    creatorsCount: 3102,
    mentions24h: 89200,
    mentionsPrev24h: 25600,
    creatorsLast6h: 520,
    creatorsLast24h: 1600,
    creatorsLast72h: 3102,
    sparklineData: [30, 42, 38, 55, 67, 72, 80, 84, 82],
    timeAgo: '1h ago',
    firstDetectedAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    hashtags: ['#InstagramBroadcast', '#Creators', '#ContentStrategy', '#IG2026'],
    description: 'Instagram Broadcast Channels are becoming the go-to for direct creator-fan communication replacing newsletters.',
    isBookmarked: false,
    velocity: 1.9,
    spike: 248,
    contentType: 'HOOK',
    trendingAudio: 'Phonk Aesthetic - Trending Beat',
    geoRegions: ['US', 'IN', 'BR'],
    geoSpreadScore: 3,
  },
  {
    id: 'trend-003',
    title: 'Agentic AI Workflows',
    category: 'AI & Tech',
    status: 'hot',
    nemoScore: 88,
    cvs: 91,
    ss: 72,
    cps: 80,
    freshness: 67,
    freshnessMultiplier: 0.67,
    platforms: ['google', 'youtube', 'linkedin', 'instagram'],
    creatorsCount: 6234,
    mentions24h: 204100,
    mentionsPrev24h: 71400,
    creatorsLast6h: 1050,
    creatorsLast24h: 3100,
    creatorsLast72h: 6234,
    sparklineData: [15, 22, 40, 38, 62, 75, 85, 90, 88],
    timeAgo: '4h ago',
    firstDetectedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    hashtags: ['#AgenticAI', '#AIAgents', '#Automation', '#AIWorkflow', '#Productivity'],
    description: 'Multi-agent AI systems and agentic workflows are taking over enterprise and creator productivity conversations.',
    isBookmarked: true,
    velocity: 2.1,
    spike: 287,
    contentType: 'CONCEPT',
    geoRegions: ['US', 'IN', 'UK', 'DE', 'SG', 'AU'],
    geoSpreadScore: 6,
    breakoutBoolean: true,
  },
  {
    id: 'trend-004',
    title: 'YouTube Shorts Monetization Update',
    category: 'Marketing',
    status: 'rising',
    nemoScore: 72,
    cvs: 65,
    ss: 58,
    cps: 42,
    freshness: 100,
    freshnessMultiplier: 1.0,
    platforms: ['youtube', 'google'],
    creatorsCount: 2891,
    mentions24h: 67300,
    mentionsPrev24h: 23400,
    creatorsLast6h: 480,
    creatorsLast24h: 1450,
    creatorsLast72h: 2891,
    sparklineData: [10, 18, 25, 22, 38, 45, 60, 68, 72],
    timeAgo: '3h ago',
    firstDetectedAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    hashtags: ['#YouTubeShorts', '#Monetization', '#Creators', '#YTPartner'],
    description: 'YouTube announced expanded Shorts monetization options giving creators new revenue streams from short-form content.',
    isBookmarked: false,
    velocity: 1.4,
    spike: 172,
    contentType: 'TOPIC',
    geoRegions: ['US', 'IN', 'UK'],
    geoSpreadScore: 3,
  },
  {
    id: 'trend-005',
    title: 'IPL 2026 Fantasy League',
    category: 'Sports',
    status: 'hot',
    nemoScore: 79,
    cvs: 72,
    ss: 62,
    cps: 62,
    freshness: 100,
    freshnessMultiplier: 1.0,
    platforms: ['google', 'instagram', 'youtube'],
    creatorsCount: 5102,
    mentions24h: 312000,
    mentionsPrev24h: 139200,
    creatorsLast6h: 850,
    creatorsLast24h: 2550,
    creatorsLast72h: 5102,
    sparklineData: [40, 55, 48, 70, 78, 74, 80, 81, 79],
    timeAgo: '30m ago',
    firstDetectedAt: new Date(Date.now() - 0.5 * 3600 * 1000).toISOString(),
    hashtags: ['#IPL2026', '#FantasyLeague', '#Cricket', '#IPLFantasy', '#Dream11'],
    description: 'IPL 2026 fantasy league discussions dominate social media with massive creator engagement around team picks.',
    isBookmarked: false,
    velocity: 1.8,
    spike: 224,
    contentType: 'TOPIC',
    geoRegions: ['IN', 'AU', 'UK', 'ZA'],
    geoSpreadScore: 4,
  },
  {
    id: 'trend-006',
    title: 'LinkedIn Thought Leadership Pods',
    category: 'Marketing',
    status: 'rising',
    nemoScore: 61,
    cvs: 54,
    ss: 45,
    cps: 3,
    freshness: 67,
    freshnessMultiplier: 0.67,
    platforms: ['linkedin'],
    creatorsCount: 1203,
    mentions24h: 31400,
    mentionsPrev24h: 16700,
    creatorsLast6h: 200,
    creatorsLast24h: 600,
    creatorsLast72h: 1203,
    sparklineData: [25, 30, 28, 35, 40, 45, 55, 60, 61],
    timeAgo: '6h ago',
    firstDetectedAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    hashtags: ['#LinkedInPods', '#ThoughtLeadership', '#B2B', '#LinkedInGrowth'],
    description: 'LinkedIn engagement pods and thought leadership strategies are seeing renewed interest as organic reach declines.',
    isBookmarked: false,
    velocity: 0.9,
    spike: 89,
    contentType: 'KEYWORD',
    geoRegions: ['US', 'UK'],
    geoSpreadScore: 2,
  },
  {
    id: 'trend-007',
    title: 'Minecraft Legends Season 3',
    category: 'Gaming',
    status: 'rising',
    nemoScore: 66,
    cvs: 60,
    ss: 52,
    cps: 62,
    freshness: 100,
    freshnessMultiplier: 1.0,
    platforms: ['youtube', 'instagram', 'google'],
    creatorsCount: 3842,
    mentions24h: 88700,
    mentionsPrev24h: 35500,
    creatorsLast6h: 640,
    creatorsLast24h: 1920,
    creatorsLast72h: 3842,
    sparklineData: [18, 24, 30, 45, 50, 55, 60, 65, 66],
    timeAgo: '1h ago',
    firstDetectedAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    hashtags: ['#MinecraftLegends', '#Gaming', '#Minecraft', '#Season3'],
    description: 'Minecraft Legends Season 3 launch is driving massive content creation across YouTube and Instagram gaming channels.',
    isBookmarked: true,
    velocity: 1.3,
    spike: 156,
    contentType: 'TOPIC',
    geoRegions: ['US', 'UK', 'BR', 'MX'],
    geoSpreadScore: 4,
  },
  {
    id: 'trend-008',
    title: 'AI-Generated Music Controversy',
    category: 'AI & Tech',
    status: 'fading',
    nemoScore: 38,
    cvs: 32,
    ss: 18,
    cps: 42,
    freshness: 33,
    freshnessMultiplier: 0.33,
    platforms: ['google', 'youtube'],
    creatorsCount: 892,
    mentions24h: 18900,
    mentionsPrev24h: 22100,
    creatorsLast6h: 80,
    creatorsLast24h: 350,
    creatorsLast72h: 892,
    sparklineData: [85, 78, 72, 65, 55, 48, 42, 39, 38],
    timeAgo: '2d ago',
    firstDetectedAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    hashtags: ['#AIMusic', '#MusicIndustry', '#AIArt', '#Copyright'],
    description: 'Debate around AI-generated music rights and copyright is cooling after peak controversy last week.',
    isBookmarked: false,
    velocity: 0.4,
    spike: -28,
    contentType: 'CONCEPT',
    geoRegions: ['US', 'UK'],
    geoSpreadScore: 2,
  },
  {
    id: 'trend-009',
    title: 'Notion AI 3.0 Features',
    category: 'Productivity',
    status: 'rising',
    nemoScore: 68,
    cvs: 61,
    ss: 55,
    cps: 45,
    freshness: 100,
    freshnessMultiplier: 1.0,
    platforms: ['youtube', 'linkedin', 'google'],
    creatorsCount: 2104,
    mentions24h: 47800,
    mentionsPrev24h: 18900,
    creatorsLast6h: 350,
    creatorsLast24h: 1050,
    creatorsLast72h: 2104,
    sparklineData: [12, 20, 28, 35, 40, 50, 58, 65, 68],
    timeAgo: '5h ago',
    firstDetectedAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    hashtags: ['#NotionAI', '#Productivity', '#PKM', '#NotionUpdate'],
    description: 'Notion AI 3.0 launch with new database intelligence features is driving tutorials and workflow breakdowns.',
    isBookmarked: false,
    velocity: 1.2,
    spike: 143,
    contentType: 'TOPIC',
    geoRegions: ['US', 'IN', 'UK'],
    geoSpreadScore: 3,
  },
  {
    id: 'trend-010',
    title: 'Finance Content Creator Boom',
    category: 'Finance',
    status: 'rising',
    nemoScore: 58,
    cvs: 50,
    ss: 42,
    cps: 45,
    freshness: 67,
    freshnessMultiplier: 0.67,
    platforms: ['youtube', 'instagram', 'linkedin'],
    creatorsCount: 1893,
    mentions24h: 43200,
    mentionsPrev24h: 19600,
    creatorsLast6h: 315,
    creatorsLast24h: 945,
    creatorsLast72h: 1893,
    sparklineData: [20, 28, 32, 38, 42, 48, 52, 56, 58],
    timeAgo: '8h ago',
    firstDetectedAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    hashtags: ['#FinanceContent', '#PersonalFinance', '#Investing', '#FinTok'],
    description: 'Personal finance creators are seeing explosive growth as Gen Z seeks financial literacy content across platforms.',
    isBookmarked: false,
    velocity: 1.1,
    spike: 118,
    contentType: 'KEYWORD',
    geoRegions: ['US', 'IN', 'UK'],
    geoSpreadScore: 3,
  },
  {
    id: 'trend-011',
    title: 'Reel Hooks Psychology',
    category: 'Marketing',
    status: 'rising',
    nemoScore: 73,
    cvs: 66,
    ss: 58,
    cps: 45,
    freshness: 100,
    freshnessMultiplier: 1.0,
    platforms: ['instagram', 'youtube', 'linkedin'],
    creatorsCount: 2654,
    mentions24h: 58900,
    mentionsPrev24h: 20000,
    creatorsLast6h: 440,
    creatorsLast24h: 1325,
    creatorsLast72h: 2654,
    sparklineData: [22, 30, 38, 44, 52, 60, 66, 71, 73],
    timeAgo: '4h ago',
    firstDetectedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    hashtags: ['#ReelHooks', '#ContentPsychology', '#Hooks', '#InstagramReels', '#ContentCreator'],
    description: 'Psychology-based hook frameworks for Reels are going viral among marketing educators and content strategy creators.',
    isBookmarked: false,
    velocity: 1.5,
    spike: 189,
    contentType: 'HOOK',
    trendingAudio: 'Lo-Fi Study Beats Vol.3',
    geoRegions: ['US', 'IN', 'UK'],
    geoSpreadScore: 3,
  },
  {
    id: 'trend-012',
    title: 'EV Charging Infrastructure India',
    category: 'Business',
    status: 'rising',
    nemoScore: 54,
    cvs: 48,
    ss: 38,
    cps: 21,
    freshness: 67,
    freshnessMultiplier: 0.67,
    platforms: ['google', 'linkedin'],
    creatorsCount: 784,
    mentions24h: 22100,
    mentionsPrev24h: 12600,
    creatorsLast6h: 130,
    creatorsLast24h: 390,
    creatorsLast72h: 784,
    sparklineData: [15, 20, 25, 30, 35, 40, 46, 52, 54],
    timeAgo: '7h ago',
    firstDetectedAt: new Date(Date.now() - 7 * 3600 * 1000).toISOString(),
    hashtags: ['#EVIndia', '#ElectricVehicles', '#EVCharging', '#GreenIndia'],
    description: 'India EV charging infrastructure expansion is driving B2B content and investment discussion on LinkedIn.',
    isBookmarked: false,
    velocity: 0.8,
    spike: 76,
    contentType: 'KEYWORD',
    geoRegions: ['IN'],
    geoSpreadScore: 1,
  },
];

export const CATEGORIES = [
  'All',
  'AI & Tech',
  'Marketing',
  'Sports',
  'Gaming',
  'Finance',
  'Business',
  'Productivity',
  'Fitness',
  'Fashion',
  'Food',
  'Travel',
  'Education',
];

export const PLATFORMS: TrendPlatform[] = ['google', 'youtube', 'instagram', 'linkedin', 'tiktok', 'twitter', 'reddit'];

export const MOCK_ADMIN_USERS = [
  { id: 'user-001', name: 'Priya Mehta', email: 'priya.mehta@studio.in', plan: 'Pro', status: 'active', joined: '2026-01-14', bookmarks: 24, apiKeys: 2 },
  { id: 'user-002', name: 'Arjun Kapoor', email: 'arjun.kapoor@creator.com', plan: 'Free', status: 'active', joined: '2026-02-03', bookmarks: 7, apiKeys: 0 },
  { id: 'user-003', name: 'Sneha Iyer', email: 'sneha.iyer@brandco.io', plan: 'Agency', status: 'active', joined: '2026-01-28', bookmarks: 51, apiKeys: 5 },
  { id: 'user-004', name: 'Rahul Verma', email: 'rahul.v@growthx.in', plan: 'Pro', status: 'active', joined: '2026-03-11', bookmarks: 18, apiKeys: 1 },
  { id: 'user-005', name: 'Divya Nair', email: 'divya.nair@contentlab.com', plan: 'Free', status: 'inactive', joined: '2026-04-05', bookmarks: 2, apiKeys: 0 },
  { id: 'user-006', name: 'Karan Singh', email: 'karan.singh@agency.co', plan: 'Agency', status: 'active', joined: '2026-02-19', bookmarks: 88, apiKeys: 8 },
  { id: 'user-007', name: 'Ananya Sharma', email: 'ananya.s@vibevault.in', plan: 'Pro', status: 'active', joined: '2026-05-01', bookmarks: 33, apiKeys: 3 },
  { id: 'user-008', name: 'Vikram Patel', email: 'vikram.patel@trendhq.com', plan: 'Free', status: 'active', joined: '2026-06-10', bookmarks: 9, apiKeys: 0 },
];

export const MOCK_API_KEYS = [
  { id: 'key-001', name: 'Production Dashboard', prefix: 'NT_prod_8f2a', lastUsed: '2026-07-12', created: '2026-06-01', requests: 4821 },
  { id: 'key-002', name: 'Content Automation Bot', prefix: 'NT_bot_3c9d', lastUsed: '2026-07-11', created: '2026-06-15', requests: 1204 },
  { id: 'key-003', name: 'Analytics Pipeline', prefix: 'NT_anl_7e1b', lastUsed: '2026-07-10', created: '2026-07-01', requests: 387 },
];

export const ANALYTICS_DAILY_DATA = [
  { day: 'Jun 15', views: 12400, engagement: 4.2 },
  { day: 'Jun 16', views: 15800, engagement: 5.1 },
  { day: 'Jun 17', views: 11200, engagement: 3.8 },
  { day: 'Jun 18', views: 18900, engagement: 6.3 },
  { day: 'Jun 19', views: 22100, engagement: 7.1 },
  { day: 'Jun 20', views: 19400, engagement: 5.9 },
  { day: 'Jun 21', views: 16700, engagement: 5.2 },
  { day: 'Jun 22', views: 24300, engagement: 7.8 },
  { day: 'Jun 23', views: 28900, engagement: 8.4 },
  { day: 'Jun 24', views: 21500, engagement: 6.5 },
  { day: 'Jun 25', views: 19800, engagement: 6.1 },
  { day: 'Jun 26', views: 31200, engagement: 9.2 },
  { day: 'Jun 27', views: 27600, engagement: 8.1 },
  { day: 'Jun 28', views: 23400, engagement: 7.0 },
  { day: 'Jun 29', views: 18100, engagement: 5.4 },
  { day: 'Jun 30', views: 20800, engagement: 6.3 },
  { day: 'Jul 01', views: 35600, engagement: 10.2 },
  { day: 'Jul 02', views: 29800, engagement: 8.9 },
  { day: 'Jul 03', views: 25100, engagement: 7.5 },
  { day: 'Jul 04', views: 22300, engagement: 6.7 },
  { day: 'Jul 05', views: 38400, engagement: 11.1 },
  { day: 'Jul 06', views: 33200, engagement: 9.8 },
  { day: 'Jul 07', views: 28700, engagement: 8.5 },
  { day: 'Jul 08', views: 26500, engagement: 7.9 },
  { day: 'Jul 09', views: 41200, engagement: 12.3 },
  { day: 'Jul 10', views: 36800, engagement: 10.8 },
  { day: 'Jul 11', views: 31400, engagement: 9.4 },
  { day: 'Jul 12', views: 28900, engagement: 8.6 },
];

export const WEEKDAY_ENGAGEMENT = [
  { day: 'Mon', score: 6.2 },
  { day: 'Tue', score: 7.8 },
  { day: 'Wed', score: 8.9 },
  { day: 'Thu', score: 9.4 },
  { day: 'Fri', score: 8.1 },
  { day: 'Sat', score: 6.5 },
  { day: 'Sun', score: 5.8 },
];

export const PLATFORM_DISTRIBUTION = [
  { name: 'Google Trends', value: 38, color: '#4285F4' },
  { name: 'YouTube Shorts', value: 28, color: '#FF0000' },
  { name: 'Instagram Reels', value: 22, color: '#E1306C' },
  { name: 'LinkedIn', value: 12, color: '#0A66C2' },
];